// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSeymSraping.Data;

namespace VotingSeymSraping.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20201116173102_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("VotingSeymSraping.Entity.Envoys", b =>
                {
                    b.Property<int>("EnvoyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("PoliticalParty")
                        .HasColumnType("TEXT");

                    b.HasKey("EnvoyID");

                    b.ToTable("Envoys");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Meetings", b =>
                {
                    b.Property<int>("NrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfVote")
                        .HasColumnType("TEXT");

                    b.Property<int>("NrMeetings")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberVoteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfVote")
                        .HasColumnType("TEXT");

                    b.Property<string>("VotingTopic")
                        .HasColumnType("TEXT");

                    b.HasKey("NrID");

                    b.HasIndex("NumberVoteId");

                    b.ToTable("Meetingses");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Votings", b =>
                {
                    b.Property<int>("NumberVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEnvoy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NameEnvoyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoteType")
                        .HasColumnType("INTEGER");

                    b.HasKey("NumberVoteId");

                    b.HasIndex("NameEnvoyID");

                    b.ToTable("Votings");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Meetings", b =>
                {
                    b.HasOne("VotingSeymSraping.Entity.Votings", "NumberVote")
                        .WithMany()
                        .HasForeignKey("NumberVoteId");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Votings", b =>
                {
                    b.HasOne("VotingSeymSraping.Entity.Envoys", "Name")
                        .WithMany()
                        .HasForeignKey("NameEnvoyID");
                });
#pragma warning restore 612, 618
        }
    }
}
