// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotingSeymSraping.Data;

namespace VotingSeymSraping.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("VotingSeymSraping.Entity.Deputy", b =>
                {
                    b.Property<int>("EnvoyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<string>("PoliticalParty")
                        .HasColumnType("TEXT");

                    b.HasKey("EnvoyID");

                    b.ToTable("Deputies");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Meeting", b =>
                {
                    b.Property<int>("NrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfVote")
                        .HasColumnType("TEXT");

                    b.Property<int>("NrMeetings")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfVote")
                        .HasColumnType("TEXT");

                    b.Property<string>("VotingTopic")
                        .HasColumnType("TEXT");

                    b.HasKey("NrID");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Vote", b =>
                {
                    b.Property<int>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MeetingNrID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameEnvoy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NameEnvoyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoteType")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoteID");

                    b.HasIndex("MeetingNrID");

                    b.HasIndex("NameEnvoyID");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VotingSeymSraping.Entity.Vote", b =>
                {
                    b.HasOne("VotingSeymSraping.Entity.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingNrID");

                    b.HasOne("VotingSeymSraping.Entity.Deputy", "Name")
                        .WithMany()
                        .HasForeignKey("NameEnvoyID");
                });
#pragma warning restore 612, 618
        }
    }
}
